name: python-isort
author: jamescurtin
description: Run isort on a Python project
branding:
  icon: check
  color: blue

inputs:
  isortVersion:
    description: Version of isort to use
    required: false
    default: 5.6.4
  sortPaths:
    description: files or directories to sort
    required: false
    default: .
  configuration:
    description: isort configuration options
    required: false
    default: --check-only --diff
  requirementsFiles:
    description:
      path(s) to requirements files that should be installed to properly
      configure third-party imports
    required: false
    default: ""

outputs:
  isort-result:
    description: isort result
    value: ${{ steps.run-isort.outputs.isort-output }}

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/bin/ensure_python
      shell: bash
    - run:
        ${{ github.action_path }}/bin/install_packages ${{ inputs.isortVersion
        }} ${{ inputs.requirementsFiles }}
      shell: bash
    - id: run-isort
      run:
        ${{ github.action_path }}/bin/run_isort ${{ inputs.configuration }} ${{
        inputs.sortPaths }}
      shell: bash
