services:
  lint:
    build:
      dockerfile: .github/linting/Dockerfile
      context: .
    volumes:
      - .github/linting/lint.sh:/usr/local/bin/lint
      - .github/linting/.yamllint:/.yamllint
      - ./:/workdir
